### ISSUE TITLE
Node.js minimum version

### ISSUE THREAD

**Issue by g3r4n** [Esri/arcgis-webpack-plugin#1]
Don't seems to work with node.js 6.14.1.
output : 
```
XXX\node_modules\@arcgis\webpack-plugin\index.js:90
    this.options = { ...this.options, ...options.options };
                     ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (XXX\config\webpack.config.dev.js:22:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
```
Working with node.js 8.11.1
What is the minimum version of node supported ?

**Comment by odoe** [comment]
I'll make it 8 later today.

**Comment by odoe** [comment]
Fixed in https://github.com/Esri/arcgis-webpack-plugin/commit/5a00a79aa2593f878dc9ce7d06a97a27a4704629
