### ISSUE TITLE
version > 4.7.2 are broken on windows

### ISSUE THREAD

**Issue by g3r4n** [Esri/arcgis-webpack-plugin#14]
The last working version on my Windows machine is version 4.7.2, i've tested every version to 4.7.9.
repository to reproduce : 
https://github.com/g3r4n/esri-js-webpack
Steps to reproduce:
* change the webpack plugin version
* run npm install
* run npm build

**Comment by g3r4n** [comment]
output fro version 4.7.10:
```
Hash: 7fc82237e557154b280f
Version: webpack 4.8.3
Time: 47285ms
Built at: 2018-05-22 09:16:57
 119 assets
Entrypoint main = main.css bundle.js
 [467] C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js 67.9 KiB {91} [built]
 [470] ./node_modules/babel-loader/lib!./src/index.css 84 bytes {91} [built]
 [471] ./node_modules/babel-loader/lib!./src/esriConfig.js 1.65 KiB {91} [built]
 [473] ./node_modules/babel-loader/lib!./src/App.css 84 bytes {91} [built]
 [816] ./node_modules/babel-loader/lib!./src/MapView.js 3.91 KiB {91} [built]
 [927] ./node_modules/moment/locale sync ^\.\/.*$ 2.81 KiB {91} [optional] [built]
 [928] (webpack)/buildin/module.js 519 bytes {91} [built]
[1105] ./node_modules/babel-loader/lib!./src/App.js 4.08 KiB {91} [built]
[1114] ./src/index.js 643 bytes {91} [built]
[1116] multi react-hot-loader/patch ./src/index.js C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js 52 bytes {91} [built]
[1143] external "./support/pe-wasm" 42 bytes {91} [built]
    + 1976 hidden modules

ERROR in ./node_modules/arcgis-js-api/themes/light/main.css
Module build failed: ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
    at handleParseError (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\webpack\lib\NormalModule.js:385:19)
    at doBuild.err (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\webpack\lib\NormalModule.js:419:5)
    at runLoaders (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\webpack\lib\NormalModule.js:280:12)
    at D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at D:\Workspace\Innovation\minimal-react-webpack-babel-setup\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ./src/index.js 1:0-19:2
 @ multi react-hot-loader/patch ./src/index.js C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [0] C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js 67.9 KiB {0} [built]
    [1] (webpack)/buildin/module.js 519 bytes {0} [built]
    [3] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 371 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/arcgis-js-api/themes/light/main.css:
     26 assets
    Entrypoint mini-css-extract-plugin = *
    [10] C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js 67.9 KiB {0} [built]
        + 53 hidden modules

    ERROR in ./node_modules/dgrid/css/images/ui-icons_222222_256x240.png
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/css-loader!./node_modules/dgrid/css/dgrid.css 7:1733-1780
     @ ./node_modules/css-loader!./node_modules/arcgis-js-api/themes/light/main.css
Child mini-css-extract-plugin node_modules/css-loader/index.js!src/App.css:
    Entrypoint mini-css-extract-plugin = *
    [0] C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js 67.9 KiB {0} [built]
    [2] ./node_modules/css-loader!./src/App.css 241 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js!src/index.css:
    Entrypoint mini-css-extract-plugin = *
    [0] C:/Users/edesvaux/AppData/Local/Temp/tmp-25420S8axo7tKb0x6/dojo/dojo.js 67.9 KiB {0} [built]
    [2] ./node_modules/css-loader!./src/index.css 252 bytes {0} [built]
        + 1 hidden module
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by odoe** [comment]
Maybe you need to delete your `node_modules`, I just tried a fresh install with `4.7.10` on Windows 10 and it works. It fixed this specific issue.

If you run into trouble, try as suggested here.
https://github.com/Esri/arcgis-webpack-plugin#asset-loaders

**Comment by g3r4n** [comment]
Fixed with : https://github.com/Esri/arcgis-webpack-plugin#asset-loaders
