### ISSUE TITLE
No hook for filter absMids in object NormalModuleFactory

### ISSUE THREAD

**Issue by atdiff** [Esri/arcgis-webpack-plugin#32]
## Description

When running webpack with the arcgis-webpack-plugin and the speed-measure-webpack-plugin, I encounter a "No hook for filter absMids in object NormalModuleFactory" error.  If I comment out the use of the arcgis-webpack-plugin, it works fine.

```
C:\myapp\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:124
                throw new Error(`No hook for ${name} in object ${obj.constructor.name}`);
                ^

Error: No hook for filter absMids in object NormalModuleFactory
    at callHook (C:\myapp\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:124:9)
    at callSync (C:\myapp\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:137:10)
    at DojoAMDModuleFactoryPlugin.module (C:\myapp\node_modules\dojo-webpack-plugin\lib\DojoAMDModuleFactoryPlugin.js:225:4)
    at SyncWaterfallHook.eval [as call] (eval at create (C:\myapp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at hooks.afterResolve.callAsync (C:\myapp\node_modules\webpack\lib\NormalModuleFactory.js:153:40)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\myapp\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:66:1)
    at resolver (C:\myapp\node_modules\webpack\lib\NormalModuleFactory.js:138:29)
    at resolver (C:\myapp\node_modules\dojo-webpack-plugin\lib\DojoAMDModuleFactoryPlugin.js:199:5)
    at process.nextTick (C:\myapp\node_modules\webpack\lib\NormalModuleFactory.js:342:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

## Expected Behavior

The build should succeed and the information of webpack build times should be displayed

## Actual Behavior

An error occurs.

## Steps to Reproduce

1. Follow the usage instructions of the speed-measure-webpack-plugin - https://github.com/stephencookdev/speed-measure-webpack-plugin#usage

## Context

Attempting to use speed-measure-webpack-plugin with the project for analysis of webpack build times

## Your Environment

* Version used: 4.9.0
* Operating System and version (desktop or mobile): Windows 10
* Node: 10.12.0
* npm: 6.4.1

**Comment by odoe** [comment]
There could be a conflict between that plugin and the underlying plugin we use. I'll try to build a test case for it.
