### ISSUE TITLE
Angular 8 CLI + ArcGIS 4.11 API ng build fails

### ISSUE THREAD

**Issue by cljubicbu** [Esri/arcgis-webpack-plugin#49]
I've created a new application with Angular CLI 8, added arcgis-webpack-plugin and adjusted all files. _ng serve_ runs fine and the application is working, but _ng build_/ _ng build -- prod_ fails with the following error:

`Hook dojoWebpackPluginOptions already registered
Error: Hook dojoWebpackPluginOptions already registered
    at events.forEach.event (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:65:10)
    at Array.forEach (<anonymous>)
    at reg (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:57:9)
    at DojoAMDPlugin.apply (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js:55:3)
    at requiredPlugins.forEach.plugin (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\@arcgis\webpack-plugin\index.js:94:46)
    at Array.forEach (<anonymous>)
    at ArcGISPlugin.apply (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\@arcgis\webpack-plugin\index.js:94:21)
    at webpack (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\webpack\lib\webpack.js:47:13)
    at options.webpackFactory.config (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:19:74)
    at Object.runWebpack (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:27:12)
    at rxjs_1.from.pipe.operators_1.mergeScan (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\@angular-devkit\build-angular\src\browser\index.js:126:40)
    at MergeScanSubscriber._next (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\rxjs\internal\operators\mergeScan.js:57:23)
    at MergeScanSubscriber.notifyComplete (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\rxjs\internal\operators\mergeScan.js:97:18)
    at InnerSubscriber._complete (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\rxjs\internal\InnerSubscriber.js:35:21)
    at InnerSubscriber.Subscriber.complete (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\rxjs\internal\Subscriber.js:78:18)
    at SwitchMapSubscriber.Subscriber._complete (C:\Users\christian.bungi\Documents\testic\testApp\node_modules\rxjs\internal\Subscriber.js:96:26)`

Node version: 10.9.0

**Comment by andygup** [comment]
Did you use a custom builder? If you didn't then your app won't work with Angular 8 and this plugin. 

In general I recommend using `esri-loader` with Angular 6 thru 8. The Angular CLI team just finally announced CLI Builders a month ago and I haven't had a chance to test using a custom builder and this plugin.

Builder announcement - https://blog.angular.io/introducing-cli-builders-d012d4489f1b
Esri-loader - https://github.com/esri/esri-loader

**Comment by TheILPlace** [comment]
@andygup 
Hi, angular 8 is out for some time now, any news about getting esri to work with the new cli builders ?

**Comment by TheILPlace** [comment]
@cljubicbu  can you share how you integrated the esri plugin with angular8 ?

**Comment by andygup** [comment]
Nope, no updates on Angular 8 + builders. I did some prototyping a couple weeks ago but nothing publishable that I really felt solid about. I'll keep pecking away at it, but if someone else comes up with a solid approach let us know about the details.

@TheILPlace here's a repo that demonstrates how to use `esri-loader` with Angular 7, with just a few small tweaks it works with Angular 8: https://github.com/Esri/angular-cli-esri-map. Here's the tweaks you need to make: https://github.com/Esri/angular-cli-esri-map/issues/32.

**Comment by RyannGalea** [comment]
Will be following this.

**Comment by andygup** [comment]
@RyannGalea for JS API + Angular 8 CLI + webpack there's a new repo here: https://github.com/Esri/angular-cli-esri-map/tree/arcgis-webpack-angular 

@odoe feel free to close this issue.
