### ISSUE TITLE
might need tapable as a dep for CRA

### ISSUE THREAD

**Issue by edejin** [Esri/arcgis-webpack-plugin#68]
It does not work

## Description
It does not work

## Expected Behavior
It should work

## Actual Behavior
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> ...@0.1.0 start /home/.../WebstormProjects/.../front
> HTTPS=true node scripts/start.js

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'tapable/package.json'
Require stack:
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/webpack-plugin-compat/index.js
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/index.js
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/index.js
- /home/.../WebstormProjects/.../front/config/webpack.config.dev.js
- /home/.../WebstormProjects/.../front/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/webpack-plugin-compat/index.js:16:32)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/webpack-plugin-compat/index.js',
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js',
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/index.js',
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/index.js',
    '/home/.../WebstormProjects/.../front/config/webpack.config.dev.js',
    '/home/.../WebstormProjects/.../front/scripts/start.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ...@0.1.0 start: `HTTPS=true node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ...@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2019-11-04T03_50_35_723Z-debug.log
```

## Possible Fix
```
npm install tapable
```
but
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> ...@0.1.0 start /home/.../WebstormProjects/.../front
> HTTPS=true node scripts/start.js

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'webpack-sources'
Require stack:
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDChunkTemplatePlugin.js
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/index.js
- /home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/index.js
- /home/.../WebstormProjects/.../front/config/webpack.config.dev.js
- /home/.../WebstormProjects/.../front/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDChunkTemplatePlugin.js:26:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js:29:36)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDChunkTemplatePlugin.js',
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js',
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/node_modules/dojo-webpack-plugin/index.js',
    '/home/.../WebstormProjects/.../node_modules/@arcgis/webpack-plugin/index.js',
    '/home/.../WebstormProjects/.../front/config/webpack.config.dev.js',
    '/home/.../WebstormProjects/.../front/scripts/start.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ...@0.1.0 start: `HTTPS=true node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ...@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2019-11-04T03_57_47_961Z-debug.log

Process finished with exit code 1
```

## Steps to Reproduce
1. `git clone git@github.com:edejin/gg.git`
2. `npm install`
3. `npm run start`

## Context

I try to use ArcGIS

## Your Environment
* Version used:
```
$ npm --version
6.12.0
$ node --version
v12.13.0
```
* Browser Name and version: any
* Operating System and version (desktop or mobile): `Linux ... 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project if available: -

**Comment by odoe** [comment]
I've listed `webpack-sources` as a `peerDependency`, maybe I could list `tapable` too. I still get an odd `resolverFactory` not defined error, so I think there might be a conflict in the version of a webpack package used by the plugin and the ejected CRA app. This is going to require a bit more digging, but updating the project dependencies might help.
