### ISSUE TITLE
"Error: No hook for resolver normal in object ResolverFactory" error on yarn/npm build

### ISSUE THREAD

**Issue by dpmarley** [Esri/arcgis-webpack-plugin#72]
## Description
I am getting the error "Error: No hook for resolver normal in object ResolverFactory" intermittently when building a web project built with Esri JS API 4.13.2 and the ArcGIS Webpack plugin.4.13.0. The error does not occur consistently, but once I do start getting it, the only solution appears to be cloning a completely fresh copy of my project repo and building from that.  I am confused as to why this error only seems to occur intermittently, and can't offer any more details as to when or why it starts occurring.

This a full trace of the build error:
```
$ yarn run start
yarn run v1.16.0
$ webpack --mode=development --watch --progress
C:\Projects\abc\xyz\en_react\node_modules\webpack-cli\bin\cli.js:281
                                throw err;
                                ^

Error: No hook for resolver normal in object ResolverFactory
    at names.forEach.name (C:\Projects\abc\xyz\en_react\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:101:11)
    at Array.forEach (<anonymous>)
    at events.forEach.event (C:\Projects\abc\xyz\en_react\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:98:9)
    at Array.forEach (<anonymous>)
    at Object.tap (C:\Projects\abc\xyz\en_react\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:93:9)
    at DojoAMDResolverPluginV4.apply (C:\Projects\abc\xyz\en_react\node_modules\dojo-webpack-plugin\lib\DojoAMDResolverPluginV4.js:28:3)
    at applyResolverPlugin (C:\Projects\abc\xyz\en_react\node_modules\dojo-webpack-plugin\lib\compat.js:55:39)
    at DojoAMDPlugin.apply (C:\Projects\abc\xyz\en_react\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js:57:3)
    at plugins.forEach.plugin (C:\Projects\abc\xyz\en_react\node_modules\@arcgis\webpack-plugin\index.js:97:38)
    at Array.forEach (<anonymous>)
    at ArcGISPlugin.apply (C:\Projects\abc\xyz\en_react\node_modules\@arcgis\webpack-plugin\index.js:97:13)
    at webpack (C:\Projects\abc\xyz\en_react\node_modules\webpack\lib\webpack.js:51:13)
    at processOptions (C:\Projects\abc\xyz\en_react\node_modules\webpack-cli\bin\cli.js:272:16)
    at yargs.parse (C:\Projects\abc\xyz\en_react\node_modules\webpack-cli\bin\cli.js:364:3)
    at Object.parse (C:\Projects\abc\xyz\en_react\node_modules\yargs\yargs.js:567:18)
    at C:\Projects\abc\xyz\en_react\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Projects\abc\xyz\en_react\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Projects\abc\xyz\en_react\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

A similar issue was noted on Geonet, though there is no clear resolution that I can see on that thread:
https://community.esri.com/thread/217740-error-no-hook-for-resolver-normal-in-object-resolverfactory

## Expected Behavior
Project should build consistently

## Actual Behavior
Project intermittently fails on yarn (or npm) build, with the error noted in the title/description.

## Possible Fix
Curious whether an update to some other dependency may resolve this (webpack, webpack-cli?, perhaps an update to dojo-webpack-plugin that is a dependency for esri-webpack-plugin?). 

## Steps to Reproduce
I have not tried to reproduce this in a generic project, at least not yet. I can't actually pinpoint when and why this error starts occurring. I typically get several successful builds, and then once the error occurs, I cannot seem to get around it without cloning a fresh copy of my repo

## Context
Unable to consistently develop/test/build my JS Api project

## Your Environment
Windows version 10.0.17134 Build 17134
Node v10.17.0
npm 6.11.3
yarn 1.16.0

Esri JS API: 4.13.2
ArcGIS webpack plugin: 4.13.0

Webpack-related dependencies in my project:
$ yarn list --depth=0 --pattern webpack
yarn list v1.16.0
├─ @arcgis/webpack-plugin@4.13.0
├─ copy-webpack-plugin@5.0.5
├─ dojo-webpack-plugin@2.8.10
├─ terser-webpack-plugin@1.4.1
├─ webpack-bundle-analyzer@3.6.0
├─ webpack-cli@3.3.10
├─ webpack-hasjs-plugin@1.0.3
├─ webpack-log@2.0.0
├─ webpack-plugin-compat@1.0.3
├─ webpack-sources@1.4.3
└─ webpack@4.41.2
Done in 0.48s.

**Comment by besLisbeth** [comment]
Did you try to remove `node_modules` and `package-lock.json` and run `npm i`? It sometimes happens after the update of the dependencies.

**Comment by dpmarley** [comment]
Thanks @besLisbeth - I did try removing those, in addition to doing `git clean -dxf`.  Still no luck.

Curiously, I had not gotten this issue in a long time, and had nearly forgotten about this, until today when I tried using `@arcgis/cli`  to create a JS API with the Vue template ( `arcgis create jsapi-vue-app -t vue` ), and on `npm start`, I get the same error.

```
$ npm start

> jsapi-vue-app@1.0.0 start C:\projects_local\vuejs\jsapi-vue-app
> webpack-dev-server --history-api-fallback --mode development --open

Error: No hook for resolver normal in object ResolverFactory
    at names.forEach.name (C:\projects_local\vuejs\jsapi-vue-app\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:101:11)
```

This template does use the `arcgis-webpack-plugin` so I am still wondering if there is some connection to the webpack plugin on this.

**Comment by elake2018** [comment]
I have been getting this as well for some time, everything seems to work so I just ignore it for now.
